### ISSUE TITLE
Memento select_raw error

### ISSUE THREAD

**Issue by Kinyugo** [sheharyarn/memento#32]
Calling `Memento.Query.select_raw(...)` leads to an error when attempting to load the results. 
```
** (FunctionClauseError) no function clause matching in Memento.Query.Data.load/1    
    
    The following arguments were given to Memento.Query.Data.load/1:
    
        # 1
        "a"
    
    Attempted function clauses (showing 1 out of 1):
    
        def load(data) when is_tuple(data)
    
    (memento 0.3.2) lib/memento/query/data.ex:55: Memento.Query.Data.load/1
    (elixir 1.13.0) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
    (mnesia 4.20.3) mnesia_tm.erl:842: :mnesia_tm.apply_fun/3
    (mnesia 4.20.3) mnesia_tm.erl:818: :mnesia_tm.execute_transaction/5
    (memento 0.3.2) lib/memento/transaction.ex:71: Memento.Transaction.execute/2
```

**Comment by sheharyarn** [comment]
Closing this because of inactivity.

If you're still having issues with this, please share your Memento table schema and the exact query you're running.
